# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "x64dbg-dbgeng"
msvc-runtime = "static"

[target.playground]
type = "executable"
sources = ["src/playground/playground.cpp"]
compile-features = ["cxx_std_20"]
link-libraries = ["DbgEng", "Delayimp"]
msvc.link-options = ["/DELAYLOAD:dbgeng.dll"]

[target.replay_probe]
type = "executable"
sources = ["src/replay_probe/replay_probe.cpp"]
compile-features = ["cxx_std_20"]
link-libraries = ["DbgEng", "Delayimp"]
msvc.link-options = ["/DELAYLOAD:dbgeng.dll"]

[target.shim_replay_probe]
type = "executable"
sources = ["src/shim_replay_probe/shim_replay_probe.cpp"]
compile-features = ["cxx_std_20"]

[target.TitanEngine]
type = "shared"
sources = [
	"src/TitanEngine/TitanEngine.cpp",
]
headers = [
	"src/TitanEngine/TitanEngine.h",
	"src/TitanEngine/FileMap.h",
]
compile-features = ["cxx_std_20"]
link-libraries = ["DbgEng", "Delayimp"]
msvc.link-options = ["/DELAYLOAD:dbgeng.dll"]

[target.testlib]
type = "shared"
msvc-runtime = "dynamic"
sources = ["src/testlib/testlib.cpp"]
msvc.link-options = ["/INCREMENTAL:NO", "/DYNAMICBASE:NO"]

[target.testapp]
type = "executable"
msvc-runtime = "dynamic"
sources = ["src/testapp/testapp.cpp", "src/testapp/debug.h"]
msvc.link-options = ["/INCREMENTAL:NO", "/DYNAMICBASE:NO"]
link-libraries = ["::testlib"]

[target.exception]
type = "executable"
sources = ["src/exception/exception.cpp"]
msvc.link-options = ["/INCREMENTAL:NO", "/DYNAMICBASE:NO"]
